### ISSUE TITLE
Ajustar visual da tela de ajuda colocando as cores em conformidade com a imagem de referencia

### ISSUE THREAD

**Issue by DEXTERNATAN** [DEXTERNATAN/VemComigo#4]
- [ ] As cores do icone (+) e (-) devem ser a seguinte cor - #7bc3bd
- [ ] As cores da borda do card da ajuda deve ser - #7bc3bd
- [ ] Substituir o amarelo do nome do card pela cor - #7bc3bd
- [ ] Implementar rolagem vertical na tela quando a tela tem muitos cards a tela não rola até o final e fica cortando o card

**Comment by DEXTERNATAN** [comment]
![erro nos cards e na rolagem da tela](https://user-images.githubusercontent.com/1324863/46832625-ebc51280-cd7c-11e8-9723-4f9f9e7e29d5.png)
