### ISSUE TITLE
Entrega da versão 1.0.0-beta

### ISSUE THREAD

**Issue by DEXTERNATAN** [DEXTERNATAN/VemComigo#83]
- [x] Colocar o texto de explicação do app da tela Quem Somos no formato justificado - Ref. Issue - #82 

- [x] Incluir foto das meninas na página **QuemSomos** - Ref. Issue - #84 

- [x] Corrigir crase das horas - Ref. Issue - #86 

- [x] Excluir símbolos Facebook e Google+ do parte da Nayara na tela Quem somos - #87 

- [x] Quando deletar o perfil redirecionar e dizer que o usuário foi deletado - #90 

- [x] Após deletar o perfil, os dados não devem aparecer na busca - #90 

- [x] Na tela de alterar perfil constar modo de viagem - #92 

- [x] Colocar como obrigatório bairro, horário e telefone no cadastro inicial e no perfil - #93 

- [x] Após logar com o facebook redirecionar o usuário para tela perfil - #94 

- [x] Retirar acento agudo da palavra Mooca - #96 

- [x] Verificar as imagens que aparecem no app (imagens da tela de busca) eles as vezes aparecem outras vezes não aparecem - #97

**Comment by DEXTERNATAN** [comment]
Feito.
